### ISSUE TITLE
Question re only objects supported

### ISSUE THREAD

**Issue by stephenh** [salesforce/observable-membrane#50]
Hey, hopefully this is okay, but I was wondering how tightly the "does not observe non-Object.prototype objects" limitation is baked in `observable-membrane`'s design.

We have a use-case of wanting to hand out "blessed" proxies to an object graph, that we started down the road of making a written-by-hand proxy for, but after googling/researching, learned about the term membrane as really what we're trying to do, and so found libraries like this one and es-membrane.

From initial impressions, es-membrane looks large & complicated (at least from the readme), vs. observable-membrane, which looks more like "just drop it in and go", which is great, really impressive in that it looks both powerful and smiple.

But the wrinkle is that we want to wrap a membrane around our ORM object graph, which has `class Author`-type objects in it.

Hence my question: what's the rationale for the no-classes limitation (other than just general scope reduction which makes a lot of sense)? Is it a super-hard constraint? 

(Fwiw maybe the rationale/"hard-ness" of this constraint could be added to the readme, for others like me who come along and wonder "...okay, that is a limitation, but _how much_ of a limitation". I.e. could we fork or PR observable-membrane to, without-fundamentally-changing it, support this. (I'd also be willing to submit a PR to update the readme with a synthesis of any answers/conversations in this issue.))

...just naively thinking off the top-of-my-head, but we generally have ~2-4 base classes that we could whitelist.

...oh wait! there is already a `valueIsObservable` option.

If we whitelisted objects that extended from our `BaseEntity` class/prototype, would things probably still "just work"?

Thanks!

**Comment by caridy** [comment]
@stephenh, that's a pretty accurate assessment of the current state of things. Yes, membranes are complicated, yes, we took many shortcuts here for the sake of simplicity and speed, and yes, it is possible to do something like this for a finite domain of object classes but there are some caveats that we will have to discuss.

We are currently exploring tagging via symbols in #48, that is a good precedent, although it marking the outputs with that symbol, not the input. Using `valueIsObservable` is an interesting proposition, that I will definitely discuss with others. Up to this point, that method was supposed to receive an already qualified proxy target, but we could make a breaking change that extends the responsibility of that method. All-in-all, from the top of my head I see two options:

1. Extend the responsibility of `valueIsObservable` in which the method will have to return true for qualifying objects (this is a non-backwards compatible change)
2. Add a tagging mechanism for special kind of objects so their proto chain can handle proxies.

Of course, it is not realistic that all objects, or all classes will work with this membrane, only those that are designed and tested to work with it will do so. Let me brainstorm with @diervo and others, and see what we can do. If you are available for a quick chat next week to discuss the set of restrictions on your class implementation, we could organize something. The gist of such restriction is that instances of your classes cannot rely on the identity of the `this` value, because the this might not be a proxy. E.g.: they cannot have private fields.

**Comment by diervo** [comment]
This made me remember the conversation we had on TC39 about Decorators proposal long time ago, where private fields presented all sort of issues when proxifying... But I think we can figure out most of the rest.

**Comment by caridy** [comment]
@stephenh here is the PR that adds an example/test for how to use branded objects and `valueIsObservable ` to achieve what you want: https://github.com/salesforce/observable-membrane/pull/51

**Comment by stephenh** [comment]
@caridy wow, thanks for that example! I'll go comment on the PR with my thoughts. Really appreciate the quick and super-helpful response.
